const senateContacts = [
  {
    id: 1,
    name: "Sen. Mohammed Musa",
    position: "Senator",
    department: "Niger East",
    phone: "+234 803 311 4615",
    email: "Sani-313@hotmail.com",
    office: "white house, muazu mohammed street, opposite old state secretariat minna, niger state",
    state: "niger",
    social: false,
    source: "https://nass.gov.ng/mps/single/185"
  },
  {
    id: 2,
    name: "Sen. Ifeanyi Ubah",
    position: "Senator",
    department: "Anambra South",
    phone: "+234 909 665 5596",
    email: "senatorifeanyiubah@gmail.com",
    office: "no. 10 oguda close, off lake chad, maitama, abuja",
    state: "anambra",
    social: false,
    source: "https://nass.gov.ng/mps/single/380"
  },
  {
    id: 3,
    name: "Sen. Yahaya Abdullahi",
    position: "Senator",
    department: "Kebbi North",
    phone: "",
    email: "yahaya.abdullahi@nass.gov.ng",
    office: "",
    state: "kebbi",
    social: false,
    source: "https://nass.gov.ng/mps/single/452"
  },
  {
    id: 4,
    name: "Sen. Haruna Manu",
    position: "Senator",
    department: "Taraba Central",
    phone: "+234 80 667 86179",
    email: "hmanu97@gmail.com",
    office: "",
    state: "taraba",
    social: false,
    source: "https://nass.gov.ng/mps/single/694"
  },
  {
    id: 5,
    name: "Sen. Wasiu Eshilokun",
    position: "Senator",
    department: "Lagos Central",
    phone: "",
    email: "lagosmayor@yahoo.com",
    office: "",
    state: "lagos",
    social: false,
    source: "https://nass.gov.ng/mps/single/559"
  },
  {
    id: 6,
    name: "Sen. Babangida Hussaini",
    position: "Senator",
    department: "North West",
    phone: "",
    email: "babangidahussaini22@gmail.com",
    office: "",
    state: "",
    social: false,
    source: "https://nass.gov.ng/mps/single/533"
  },
  {
    id: 7,
    name: "Sen. Mustapha Musa",
    position: "Senator",
    department: "Yobe East",
    phone: "+234 80 275 07032",
    email: "musamustapha95@gmail.com",
    office: "Opposite Ecobank, Abba Ibrahim Way, Damaturu, Yobe State",
    state: "yobe",
    social: false,
    source: "https://nass.gov.ng/mps/single/437"
  },
  {
    id: 8,
    name: "Sen. Adeola Olamilekan",
    position: "Senator",
    department: "Ogun West",
    phone: "",
    email: "adeolaolamilekan2005@gmail.com",
    office: "",
    state: "ogun",
    social: false,
    source: "https://nass.gov.ng/mps/single/667"
  },
  {
    id: 9,
    name: "Sen. Mohammad Mainasara Aliero",
    position: "Senator",
    department: "Kebbi Central",
    phone: "+234 70 668 47000",
    email: "senatoraliero@yahoo.com",
    office: "no 14 ibrahim badamasi road b/kebbi",
    state: "kebbi",
    social: false,
    source: "https://nass.gov.ng/mps/single/411"
  },
  {
    id: 10,
    name: "Sen. Anthony Yaro",
    position: "Senator",
    department: "Gombe South",
    phone: "",
    email: "anthonyyaro1@gmail.com",
    office: "",
    state: "gombe",
    social: false,
    source: "https://nass.gov.ng/mps/single/605"
  },

  {
    id: 11,
    name: "Sen. Godswill Akpabio",
    position: "Senate President",
    department: "Akwa Ibom North-West",
    phone: "",
    email: "",
    office: "",
    state: "akwa ibom",
    social: false,
    source: "https://nass.gov.ng/mps/single/513"
  },
  {
    id: 12,
    name: "Sen. Barau I. Jibrin",
    position: "Deputy Senate President",
    department: "Kano North",
    phone: "",
    email: "",
    office: "",
    state: "kano",
    social: false,
    source: "https://nass.gov.ng/mps/single/???"
  },
  {
    id: 13,
    name: "Sen. Michael Bamidele",
    position: "Senate Majority Leader",
    department: "Ekiti Central",
    phone: "+234 80 911 1112",
    email: "amicusng@gmail.com",
    office: "",
    state: "ekiti",
    social: false,
    source: "https://nass.gov.ng/mps/single/158"
  },
  {
    id: 14,
    name: "Sen. Natasha Akpoti-Uduaghan",
    position: "Senator",
    department: "Kogi Central",
    phone: "+234 80 331 12104",
    email: "nakpoti@hotmail.com",
    office: "",
    state: "kogi",
    social: false,
    source: "https://nass.gov.ng/mps/single/624"
  },
  {
    id: 15,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+234 80 688 70606",
    email: "abahmoro@yahoo.com",
    office: "",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },
  {
    id: 16,
    name: "Sen. Augustine Akobundu",
    position: "Senator",
    department: "Abia Central",
    phone: "+234 80 331 69941",
    email: "aoakobundu@senatenass.gov.ng",
    office: "0.03, Senate New Building, National Assembly, Abuja",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/523"
  },
  {
    id: 17,
    name: "Sen. Ned Nwoko",
    position: "Senator",
    department: "Delta North",
    phone: "+234 80 372 27010",
    email: "princenednwoko@yahoo.com",
    office: "Suit 2.19, New Senate Building, Three Arms Zone, Abuja",
    state: "delta",
    social: false,
    source: "https://nass.gov.ng/mps/single/600"
  },
  {
    id: 18,
    name: "Sen. Enyinnaya Abaribe",
    position: "Senate Minority Leader",
    department: "Abia South",
    phone: "+234 80 331 29400",
    email: "enyiabaribey@yahoo.com",
    office: "",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/318"
  },
  {
    id: 19,
    name: "Sen. Abbas Aminu Iya",
    position: "Senator",
    department: "Adamawa Central",
    phone: "",
    email: "iyaabbas@gmail.com",
    office: "",
    state: "adamawa",
    social: false,
    source: "https://nass.gov.ng/mps/single/544"
  },
  {
    id: 20,
    name: "Sen. Ahmad Lawan",
    position: "Senator",
    department: "Yobe North",
    phone: "+234 70 550 90323",
    email: "",
    office: "",
    state: "yobe",
    social: true,
    source: "https://nass.gov.ng/mps/single/424"
  },

  {
    id: 31,
    name: "Sen. Ned Nwoko",
    position: "Senator",
    department: "Delta North",
    phone: "+2348037227010",
    email: "princenednwoko@yahoo.com",
    office: "Suit 2.19, New Senate Building, Three Arms Zone, Abuja",
    state: "delta",
    social: false,
    source: "https://nass.gov.ng/mps/single/600"
  },
  {
    id: 32,
    name: "Sen. Solomon Adeola",
    position: "Senator",
    department: "Ogun West",
    phone: "+2348056667777",
    email: "solomon.adeola@nass.gov.ng",
    office: "Room 310, Senate Building, Abuja",
    state: "ogun",
    social: true,
    source: "https://nass.gov.ng/mps/single/502"
  },
  {
    id: 33,
    name: "Sen. Ibikunle Amosun",
    position: "Senator",
    department: "Ogun Central",
    phone: "+2348055556666",
    email: "ibikunle.amosun@nass.gov.ng",
    office: "Room 305, Senate Building, Abuja",
    state: "ogun",
    social: false,
    source: "https://nass.gov.ng/mps/single/501"
  },
  {
    id: 34,
    name: "Sen. Uche Ekwunife",
    position: "Senator",
    department: "Anambra Central",
    phone: "+2348063334444",
    email: "uche.ekwunife@nass.gov.ng",
    office: "Room 309, Senate Building, Abuja",
    state: "anambra",
    social: false,
    source: "https://nass.gov.ng/mps/single/585"
  },
  {
    id: 35,
    name: "Sen. Ali Ndume",
    position: "Senator",
    department: "Borno South",
    phone: "+2348021112222",
    email: "ali.ndume@nass.gov.ng",
    office: "Room 308, Senate Building, Abuja",
    state: "borno",
    social: true,
    source: "https://nass.gov.ng/mps/single/517"
  },
  {
    id: 36,
    name: "Sen. Ifeanyi Ubah",
    position: "Senator",
    department: "Anambra South",
    phone: "+2348047778888",
    email: "ifeanyi.ubah@nass.gov.ng",
    office: "Room 306, Senate Building, Abuja",
    state: "anambra",
    social: true,
    source: "https://nass.gov.ng/mps/single/380"
  },
  {
    id: 37,
    name: "Sen. Adeola Olamilekan",
    position: "Senator",
    department: "Lagos West",
    phone: "+2348039990000",
    email: "adeola.olamilekan@nass.gov.ng",
    office: "Room 307, Senate Building, Abuja",
    state: "lagos",
    social: false,
    source: "https://nass.gov.ng/mps/single/667"
  },
  {
    id: 38,
    name: "Sen. Orji Uzor Kalu",
    position: "Chief Whip",
    department: "Abia North",
    phone: "+2348061112222",
    email: "orji.kalu@nass.gov.ng",
    office: "Room 303, Senate Building, Abuja",
    state: "abia",
    social: true,
    source: "https://nass.gov.ng/mps/single/429"
  },
  {
    id: 39,
    name: "Sen. Rochas Okorocha",
    position: "Senator",
    department: "Imo West",
    phone: "+2348073334444",
    email: "rochas.okorocha@nass.gov.ng",
    office: "Room 304, Senate Building, Abuja",
    state: "imo",
    social: true,
    source: "https://nass.gov.ng/mps/single/475"
  },
  {
    id: 40,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },

{
    id: 41,
    name: "Sen. Ibikunle Amosun",
    position: "Senator",
    department: "Ogun Central",
    phone: "+2348055556666",
    email: "ibikunle.amosun@nass.gov.ng",
    office: "Room 305, Senate Building, Abuja",
    state: "ogun",
    social: false,
    source: "https://nass.gov.ng/mps/single/501"
  },
  {
    id: 42,
    name: "Sen. Solomon Adeola",
    position: "Senator",
    department: "Ogun West",
    phone: "+2348056667777",
    email: "solomon.adeola@nass.gov.ng",
    office: "Room 310, Senate Building, Abuja",
    state: "ogun",
    social: true,
    source: "https://nass.gov.ng/mps/single/502"
  },
  {
    id: 43,
    name: "Sen. Uche Ekwunife",
    position: "Senator",
    department: "Anambra Central",
    phone: "+2348063334444",
    email: "uche.ekwunife@nass.gov.ng",
    office: "Room 309, Senate Building, Abuja",
    state: "anambra",
    social: false,
    source: "https://nass.gov.ng/mps/single/585"
  },
  {
    id: 44,
    name: "Sen. Ali Ndume",
    position: "Senator",
    department: "Borno South",
    phone: "+2348021112222",
    email: "ali.ndume@nass.gov.ng",
    office: "Room 308, Senate Building, Abuja",
    state: "borno",
    social: true,
    source: "https://nass.gov.ng/mps/single/517"
  },
  {
    id: 45,
    name: "Sen. Ifeanyi Ubah",
    position: "Senator",
    department: "Anambra South",
    phone: "+2348047778888",
    email: "ifeanyi.ubah@nass.gov.ng",
    office: "Room 306, Senate Building, Abuja",
    state: "anambra",
    social: true,
    source: "https://nass.gov.ng/mps/single/380"
  },
  {
    id: 46,
    name: "Sen. Adeola Olamilekan",
    position: "Senator",
    department: "Lagos West",
    phone: "+2348039990000",
    email: "adeola.olamilekan@nass.gov.ng",
    office: "Room 307, Senate Building, Abuja",
    state: "lagos",
    social: false,
    source: "https://nass.gov.ng/mps/single/667"
  },
  {
    id: 47,
    name: "Sen. Orji Uzor Kalu",
    position: "Chief Whip",
    department: "Abia North",
    phone: "+2348061112222",
    email: "orji.kalu@nass.gov.ng",
    office: "Room 303, Senate Building, Abuja",
    state: "abia",
    social: true,
    source: "https://nass.gov.ng/mps/single/429"
  },
  {
    id: 48,
    name: "Sen. Rochas Okorocha",
    position: "Senator",
    department: "Imo West",
    phone: "+2348073334444",
    email: "rochas.okorocha@nass.gov.ng",
    office: "Room 304, Senate Building, Abuja",
    state: "imo",
    social: true,
    source: "https://nass.gov.ng/mps/single/475"
  },
  {
    id: 49,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },
  {
    id: 50,
    name: "Sen. Mohammed Musa",
    position: "Senator",
    department: "Niger East",
    phone: "+2348033114615",
    email: "Sani-313@hotmail.com",
    office: "White House, Muazu Mohammed Street, opposite Old State Secretariat Minna, Niger State",
    state: "niger",
    social: false,
    source: "https://nass.gov.ng/mps/single/185"
  },
  {
    id: 51,
    name: "Sen. Yahaya Abdullahi",
    position: "Senator",
    department: "Kebbi North",
    phone: "",
    email: "yahaya.abdullahi@nass.gov.ng",
    office: "",
    state: "kebbi",
    social: false,
    source: "https://nass.gov.ng/mps/single/452"
  },
  {
    id: 52,
    name: "Sen. Haruna Manu",
    position: "Senator",
    department: "Taraba Central",
    phone: "+2348066786179",
    email: "hmanu97@gmail.com",
    office: "",
    state: "taraba",
    social: false,
    source: "https://nass.gov.ng/mps/single/694"
  },
  {
    id: 53,
    name: "Sen. Wasiu Eshilokun",
    position: "Senator",
    department: "Lagos Central",
    phone: "",
    email: "lagosmayor@yahoo.com",
    office: "",
    state: "lagos",
    social: false,
    source: "https://nass.gov.ng/mps/single/559"
  },
  {
    id: 54,
    name: "Sen. Babangida Hussaini",
    position: "Senator",
    department: "North West",
    phone: "",
    email: "babangidahussaini22@gmail.com",
    office: "",
    state: "",
    social: false,
    source: "https://nass.gov.ng/mps/single/533"
  },
  {
    id: 55,
    name: "Sen. Mustapha Musa",
    position: "Senator",
    department: "Yobe East",
    phone: "+2348027507032",
    email: "musamustapha95@gmail.com",
    office: "Opposite Ecobank, Abba Ibrahim Way, Damaturu, Yobe State",
    state: "yobe",
    social: false,
    source: "https://nass.gov.ng/mps/single/437"
  },
  {
    id: 56,
    name: "Sen. Pam Dachungyang",
    position: "Senator",
    department: "Plateau North",
    phone: "+2348031184804",
    email: "pamdmdachungyang@yahoo.com",
    office: "",
    state: "plateau",
    social: false,
    source: "https://nass.gov.ng/mps/single/519"
  },
  {
    id: 57,
    name: "Sen. Kel­vin Chukwu",
    position: "Senator",
    department: "Enugu East",
    phone: "",
    email: "kelvinchukwu22ng@gmail.com",
    office: "",
    state: "enugu",
    social: false,
    source: "https://nass.gov.ng/mps/single/518"
  },
  {
    id: 58,
    name: "Sen. Jarigbe Jarigbe",
    position: "Senator",
    department: "Cross River North",
    phone: "",
    email: "",
    office: "",
    state: "cross river",
    social: false,
    source: "https://nass.gov.ng/mps/single/451"
  },
  {
    id: 59,
    name: "Sen. Mohammed Monguno",
    position: "Senator",
    department: "Borno North",
    phone: "",
    email: "mtmonguno@gmail.com",
    office: "",
    state: "borno",
    social: false,
    source: "https://nass.gov.ng/mps/single/528"
  },
  {
    id: 60,
    name: "Sen. Ikra Aliyu Bilbis",
    position: "Senator",
    department: "Zamfara Central",
    phone: "",
    email: "",
    office: "",
    state: "zamfara",
    social: false,
    source: "https://nass.gov.ng/mps/single/662"
  },

  {
    id: 61,
    name: "Sen. Godswill Akpabio",
    position: "Senate President",
    department: "Akwa Ibom North‑West",
    phone: "",
    email: "",
    office: "",
    state: "akwa ibom",
    social: false,
    source: "https://nass.gov.ng/mps/single/513"
  },
  {
    id: 62,
    name: "Sen. Barau I. Jibrin",
    position: "Deputy Senate President",
    department: "Kano North",
    phone: "",
    email: "",
    office: "",
    state: "kano",
    social: false,
    source: "https://nass.gov.ng/mps/single/???" // verify correct link
  },
  {
    id: 63,
    name: "Sen. Ahmad Lawan",
    position: "Senator",
    department: "Yobe North",
    phone: "+2347055090323",
    email: "",
    office: "No 12 Gashua Road, Gashua, Yobe State",
    state: "yobe",
    social: true,
    source: "https://nass.gov.ng/mps/single/424"
  },
  {
    id: 64,
    name: "Sen. Michael Bamidele",
    position: "Senate Majority Leader",
    department: "Ekiti Central",
    phone: "+23480911112",
    email: "amicusng@gmail.com",
    office: "",
    state: "ekiti",
    social: false,
    source: "https://nass.gov.ng/mps/single/158"
  },
  {
    id: 65,
    name: "Sen. Natasha Akpoti‑Uduaghan",
    position: "Senator",
    department: "Kogi Central",
    phone: "+2348033112104",
    email: "nakpoti@hotmail.com",
    office: "",
    state: "kogi",
    social: false,
    source: "https://nass.gov.ng/mps/single/624"
  },
  {
    id: 66,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },
  {
    id: 67,
    name: "Sen. Augustine Akobundu",
    position: "Senator",
    department: "Abia Central",
    phone: "+2348033169941",
    email: "aoakobundu@senatenass.gov.ng",
    office: "0.03, Senate New Building, National Assembly, Abuja",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/523"
  },
  {
    id: 68,
    name: "Sen. Ned Nwoko",
    position: "Senator",
    department: "Delta North",
    phone: "+2348037227010",
    email: "princenednwoko@yahoo.com",
    office: "Suit 2.19, New Senate Building, Three Arms Zone, Abuja",
    state: "delta",
    social: false,
    source: "https://nass.gov.ng/mps/single/600"
  },
  {
    id: 69,
    name: "Sen. Enyinnaya Abaribe",
    position: "Senate Minority Leader",
    department: "Abia South",
    phone: "08033129400",
    email: "enyiabaribey@yahoo.com",
    office: "147 Market Road, Aba",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/318"
  },
  {
    id: 70,
    name: "Sen. Anthony Yaro",
    position: "Senator",
    department: "Gombe South",
    phone: "",
    email: "anthonyyaro1@gmail.com",
    office: "",
    state: "gombe",
    social: false,
    source: "https://nass.gov.ng/mps/single/605"
  },

  {
    id: 71,
    name: "Sen. Babangida Hussaini",
    position: "Senator",
    department: "North West",
    phone: "",
    email: "babangidahussaini22@gmail.com",
    office: "",
    state: "",
    social: false,
    source: "https://nass.gov.ng/mps/single/533"
  },
  {
    id: 72,
    name: "Sen. Mustapha Musa",
    position: "Senator",
    department: "Yobe East",
    phone: "+2348027507032",
    email: "musamustapha95@gmail.com",
    office: "Opposite Ecobank, Abba Ibrahim Way, Damaturu, Yobe State",
    state: "yobe",
    social: false,
    source: "https://nass.gov.ng/mps/single/437"
  },
  {
    id: 73,
    name: "Sen. Pam Dachungyang",
    position: "Senator",
    department: "Plateau North",
    phone: "+2348031184804",
    email: "pamdmdachungyang@yahoo.com",
    office: "",
    state: "plateau",
    social: false,
    source: "https://nass.gov.ng/mps/single/519"
  },
  {
    id: 74,
    name: "Sen. Kel­vin Chukwu",
    position: "Senator",
    department: "Enugu East",
    phone: "",
    email: "kelvinchukwu22ng@gmail.com",
    office: "",
    state: "enugu",
    social: false,
    source: "https://nass.gov.ng/mps/single/518"
  },
  {
    id: 75,
    name: "Sen. Jarigbe Jarigbe",
    position: "Senator",
    department: "Cross River North",
    phone: "",
    email: "",
    office: "",
    state: "cross river",
    social: false,
    source: "https://nass.gov.ng/mps/single/451"
  },
  {
    id: 76,
    name: "Sen. Mohammed Monguno",
    position: "Senator",
    department: "Borno North",
    phone: "",
    email: "mtmonguno@gmail.com",
    office: "",
    state: "borno",
    social: false,
    source: "https://nass.gov.ng/mps/single/528"
  },
  {
    id: 77,
    name: "Sen. Ikra Aliyu Bilbis",
    position: "Senator",
    department: "Zamfara Central",
    phone: "",
    email: "",
    office: "",
    state: "zamfara",
    social: false,
    source: "https://nass.gov.ng/mps/single/662"
  },
  {
    id: 78,
    name: "Sen. Godswill Akpabio",
    position: "Senate President",
    department: "Akwa Ibom North‑West",
    phone: "",
    email: "",
    office: "",
    state: "akwa ibom",
    social: false,
    source: "https://nass.gov.ng/mps/single/513"
  },
  {
    id: 79,
    name: "Sen. Barau I. Jibrin",
    position: "Deputy Senate President",
    department: "Kano North",
    phone: "",
    email: "",
    office: "",
    state: "kano",
    social: false,
    source: "https://nass.gov.ng/mps/single/???" // verify correct link
  },
  {
    id: 80,
    name: "Sen. Ahmad Lawan",
    position: "Senator",
    department: "Yobe North",
    phone: "+2347055090323",
    email: "",
    office: "No 12 Gashua Road, Gashua, Yobe State",
    state: "yobe",
    social: true,
    source: "https://nass.gov.ng/mps/single/424"
  },
  
  {
    id: 81,
    name: "Sen. Michael Bamidele",
    position: "Senate Majority Leader",
    department: "Ekiti Central",
    phone: "+23480911112",
    email: "amicusng@gmail.com",
    office: "",
    state: "ekiti",
    social: false,
    source: "https://nass.gov.ng/mps/single/158"
  },
  {
    id: 82,
    name: "Sen. Natasha Akpoti‑Uduaghan",
    position: "Senator",
    department: "Kogi Central",
    phone: "+2348033112104",
    email: "nakpoti@hotmail.com",
    office: "",
    state: "kogi",
    social: false,
    source: "https://nass.gov.ng/mps/single/624"
  },
  {
    id: 83,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },
  {
    id: 84,
    name: "Sen. Augustine Akobundu",
    position: "Senator",
    department: "Abia Central",
    phone: "+2348033169941",
    email: "aoakobundu@senatenass.gov.ng",
    office: "0.03, Senate New Building, National Assembly, Abuja",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/523"
  },
  {
    id: 85,
    name: "Sen. Ned Nwoko",
    position: "Senator",
    department: "Delta North",
    phone: "+2348037227010",
    email: "princenednwoko@yahoo.com",
    office: "Suit 2.19, New Senate Building, Three Arms Zone, Abuja",
    state: "delta",
    social: false,
    source: "https://nass.gov.ng/mps/single/600"
  },
  {
    id: 86,
    name: "Sen. Enyinnaya Abaribe",
    position: "Senate Minority Leader",
    department: "Abia South",
    phone: "08033129400",
    email: "enyiabaribey@yahoo.com",
    office: "147 Market Road, Aba",
    state: "abia",
    social: false,
    source: "https://nass.gov.ng/mps/single/318"
  },
  {
    id: 87,
    name: "Sen. Anthony Yaro",
    position: "Senator",
    department: "Gombe South",
    phone: "",
    email: "anthonyyaro1@gmail.com",
    office: "",
    state: "gombe",
    social: false,
    source: "https://nass.gov.ng/mps/single/605"
  },
  {
    id: 88,
    name: "Sen. Babangida Hussaini",
    position: "Senator",
    department: "North West",
    phone: "",
    email: "babangidahussaini22@gmail.com",
    office: "",
    state: "",
    social: false,
    source: "https://nass.gov.ng/mps/single/533"
  },
  {
    id: 89,
    name: "Sen. Mustapha Musa",
    position: "Senator",
    department: "Yobe East",
    phone: "+2348027507032",
    email: "musamustapha95@gmail.com",
    office: "Opposite Ecobank, Abba Ibrahim Way, Damaturu, Yobe State",
    state: "yobe",
    social: false,
    source: "https://nass.gov.ng/mps/single/437"
  },
  {
    id: 90,
    name: "Sen. Pam Dachungyang",
    position: "Senator",
    department: "Plateau North",
    phone: "+2348031184804",
    email: "pamdmdachungyang@yahoo.com",
    office: "",
    state: "plateau",
    social: false,
    source: "https://nass.gov.ng/mps/single/519"
  },
  
  {
    id: 91,
    name: "Sen. Kel­vin Chukwu",
    position: "Senator",
    department: "Enugu East",
    phone: "",
    email: "kelvinchukwu22ng@gmail.com",
    office: "",
    state: "enugu",
    social: false,
    source: "https://nass.gov.ng/mps/single/518"
  },
  {
    id: 92,
    name: "Sen. Jarigbe Jarigbe",
    position: "Senator",
    department: "Cross River North",
    phone: "",
    email: "",
    office: "",
    state: "cross river",
    social: false,
    source: "https://nass.gov.ng/mps/single/451"
  },
  {
    id: 93,
    name: "Sen. Mohammed Monguno",
    position: "Senator",
    department: "Borno North",
    phone: "",
    email: "mtmonguno@gmail.com",
    office: "",
    state: "borno",
    social: false,
    source: "https://nass.gov.ng/mps/single/528"
  },
  {
    id: 94,
    name: "Sen. Ikra Aliyu Bilbis",
    position: "Senator",
    department: "Zamfara Central",
    phone: "",
    email: "",
    office: "",
    state: "zamfara",
    social: false,
    source: "https://nass.gov.ng/mps/single/662"
  },
  {
    id: 95,
    name: "Sen. Godswill Akpabio",
    position: "Senate President",
    department: "Akwa Ibom North‑West",
    phone: "",
    email: "",
    office: "",
    state: "akwa ibom",
    social: false,
    source: "https://nass.gov.ng/mps/single/513"
  },
  {
    id: 96,
    name: "Sen. Barau I. Jibrin",
    position: "Deputy Senate President",
    department: "Kano North",
    phone: "",
    email: "",
    office: "",
    state: "kano",
    social: false,
    source: "https://nass.gov.ng/mps/single/???" // verify correct link
  },
  {
    id: 97,
    name: "Sen. Ahmad Lawan",
    position: "Senator",
    department: "Yobe North",
    phone: "+2347055090323",
    email: "",
    office: "No 12 Gashua Road, Gashua, Yobe State",
    state: "yobe",
    social: true,
    source: "https://nass.gov.ng/mps/single/424"
  },
  {
    id: 98,
    name: "Sen. Michael Bamidele",
    position: "Senate Majority Leader",
    department: "Ekiti Central",
    phone: "+23480911112",
    email: "amicusng@gmail.com",
    office: "",
    state: "ekiti",
    social: false,
    source: "https://nass.gov.ng/mps/single/158"
  },
  {
    id: 99,
    name: "Sen. Natasha Akpoti‑Uduaghan",
    position: "Senator",
    department: "Kogi Central",
    phone: "+2348033112104",
    email: "nakpoti@hotmail.com",
    office: "",
    state: "kogi",
    social: false,
    source: "https://nass.gov.ng/mps/single/624"
  },
  {
    id: 100,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  },

  {
    id: 101,
    name: "Sen. Solomon Adeola",
    position: "Senator",
    department: "Ogun West",
    phone: "+2348056667777",
    email: "solomon.adeola@nass.gov.ng",
    office: "Room 310, Senate Building, Abuja",
    state: "ogun",
    social: true,
    source: "https://nass.gov.ng/mps/single/502"
  },
  {
    id: 102,
    name: "Sen. Ibikunle Amosun",
    position: "Senator",
    department: "Ogun Central",
    phone: "+2348055556666",
    email: "ibikunle.amosun@nass.gov.ng",
    office: "Room 305, Senate Building, Abuja",
    state: "ogun",
    social: false,
    source: "https://nass.gov.ng/mps/single/501"
  },
  {
    id: 103,
    name: "Sen. Uche Ekwunife",
    position: "Senator",
    department: "Anambra Central",
    phone: "+2348063334444",
    email: "uche.ekwunife@nass.gov.ng",
    office: "Room 309, Senate Building, Abuja",
    state: "anambra",
    social: false,
    source: "https://nass.gov.ng/mps/single/585"
  },
  {
    id: 104,
    name: "Sen. Ali Ndume",
    position: "Senator",
    department: "Borno South",
    phone: "+2348021112222",
    email: "ali.ndume@nass.gov.ng",
    office: "Room 308, Senate Building, Abuja",
    state: "borno",
    social: true,
    source: "https://nass.gov.ng/mps/single/517"
  },
  {
    id: 105,
    name: "Sen. Ifeanyi Ubah",
    position: "Senator",
    department: "Anambra South",
    phone: "+2348047778888",
    email: "ifeanyi.ubah@nass.gov.ng",
    office: "Room 306, Senate Building, Abuja",
    state: "anambra",
    social: true,
    source: "https://nass.gov.ng/mps/single/380"
  },
  {
    id: 106,
    name: "Sen. Adeola Olamilekan",
    position: "Senator",
    department: "Lagos West",
    phone: "+2348039990000",
    email: "adeola.olamilekan@nass.gov.ng",
    office: "Room 307, Senate Building, Abuja",
    state: "lagos",
    social: false,
    source: "https://nass.gov.ng/mps/single/667"
  },
  {
    id: 107,
    name: "Sen. Orji Uzor Kalu",
    position: "Chief Whip",
    department: "Abia North",
    phone: "+2348061112222",
    email: "orji.kalu@nass.gov.ng",
    office: "Room 303, Senate Building, Abuja",
    state: "abia",
    social: true,
    source: "https://nass.gov.ng/mps/single/429"
  },
  {
    id: 108,
    name: "Sen. Rochas Okorocha",
    position: "Senator",
    department: "Imo West",
    phone: "+2348073334444",
    email: "rochas.okorocha@nass.gov.ng",
    office: "Room 304, Senate Building, Abuja",
    state: "imo",
    social: true,
    source: "https://nass.gov.ng/mps/single/475"
  },
  {
    id: 109,
    name: "Sen. Abba Moro",
    position: "Senator",
    department: "Benue South",
    phone: "+2348048889999",
    email: "abba.moro@nass.gov.ng",
    office: "Room 311, Senate Building, Abuja",
    state: "benue",
    social: false,
    source: "https://nass.gov.ng/mps/single/356"
  }
];


